### ISSUE TITLE
Where to find your Article 

### ISSUE THREAD

**Issue by spitalnyd** [CharlieCamp98/personal_website#1]
missing and can't find your article

**Comment by CharlieCamp98** [comment]
I just reconfigured the way in which I post articles to the site -- requiring .txt files now.

Check out the README.md file to find out where my articles are.

**Comment by spitalnyd** [comment]
Still having issues finding your website

**Comment by CharlieCamp98** [comment]
My website is accessible via www.charliecampanella.com

**Comment by spitalnyd** [comment]
okay thankyou

**Comment by spitalnyd** [comment]
also my website is now visible
