### ISSUE TITLE
Article 4 issues

### ISSUE THREAD

**Issue by cookc3174** [CharlieCamp98/personal_website#6]
The problem you have stated could be considered a real world problem. It makes sense that assignments that only go over the basic functions and definitions of problems will increase the likelihood of plagiarism. I agree that if the academic standard is raised it will be harder for people to plagiarize. When you write the paper maybe you could include: 1. some examples of how standard academics are too basic. 2. Thoroughly explain your problem so readers don't get confused.

**Comment by CharlieCamp98** [comment]
Thanks for the feedback!
